"""Per-session token authentication for the local MuxMelt backend.

Kept dependency-free (stdlib only) so the security decision can be unit-tested
in isolation, without importing the torch/fastapi-laden server module.

The token is generated by the Electron main process and handed to the renderer
over IPC. Other local processes or web pages cannot obtain it, so requiring it
on every request/WebSocket closes the otherwise-open local attack surface
(arbitrary file read/write via the upscaler/bg-remover/etc. sockets).
"""

import re
from urllib.parse import parse_qs

_LOCAL_ORIGIN_RE = re.compile(r'^https?://(localhost|127\.0\.0\.1)(:\d+)?$')


def origin_allowed(origin):
    """Renderer file:// pages send no Origin or the literal 'null'. Anything
    else must be an explicit localhost origin (defence in depth)."""
    return (
        origin is None
        or origin == 'null'
        or bool(_LOCAL_ORIGIN_RE.match(origin))
    )


def request_authorized(scope, expected_token):
    """Pure auth decision for an ASGI scope. Returns True if the request may
    proceed. When no token is configured (dev/manual runs) everything is
    allowed, preserving the previous behaviour."""
    if not expected_token:
        return True

    scope_type = scope.get('type')
    if scope_type not in ('http', 'websocket'):
        return True

    # CORS preflight carries no token and reveals nothing; let it through.
    if scope_type == 'http' and scope.get('method') == 'OPTIONS':
        return True

    qs = parse_qs(scope.get('query_string', b'').decode('latin-1'))
    provided = (qs.get('token') or [None])[0]
    if provided != expected_token:
        return False

    origin = None
    for key, value in scope.get('headers') or []:
        if key == b'origin':
            origin = value.decode('latin-1')
            break
    return origin_allowed(origin)


async def _send_forbidden(send):
    await send({
        'type': 'http.response.start',
        'status': 403,
        'headers': [(b'content-type', b'text/plain; charset=utf-8')],
    })
    await send({'type': 'http.response.body', 'body': b'Forbidden'})


class TokenAuthMiddleware:
    """ASGI middleware enforcing the token on both HTTP and WebSocket scopes.

    ``get_token`` is a callable so the token can be set after the middleware
    stack is constructed (it is parsed from argv at startup)."""

    def __init__(self, app, get_token):
        self.app = app
        self.get_token = get_token

    async def __call__(self, scope, receive, send):
        scope_type = scope.get('type')
        if scope_type in ('http', 'websocket'):
            if not request_authorized(scope, self.get_token()):
                if scope_type == 'websocket':
                    # Reject the handshake before accept -> client sees failure.
                    await send({'type': 'websocket.close', 'code': 1008})
                else:
                    await _send_forbidden(send)
                return
        await self.app(scope, receive, send)
